# Data Structures and Algorithms - Final Project
# Makefile of /ext
#
# Make sure $(DSA) is set to the root of this project

include $(DSA)/Makefile.inc

.PHONY: all src lib clean

all: src lib
	@echo > /dev/null

src:
	@( cd zedwood ; $(MAKE) src )

lib:
	@( cd zedwood ; $(MAKE) lib )

clean:
	@( cd zedwood ; $(MAKE) clean )
