# Data Structures and Algorithms - Final Project
# Makefile of /ext
#
# Make sure $(DSA) is set to the root of this project

include $(DSA)/Makefile.inc

.PHONY: all zedwood clean

all: zedwood

zedwood:
	( cd zedwood ; $(MAKE) all )

clean:
	( cd zedwood ; $(MAKE) clean )
