# Data Structures and Algorithms - Final Project
# Makefile of /src
#
# Make sure $(DSA) is set to the root of this project

include $(DSA)/Makefile.inc

.PHONY: all core clean

all: core

core:
	( cd core ; $(MAKE) all )

clean:
	( cd core ; $(MAKE) clean )
