# Data Structures and Algorithms - Final Project
# Makefile of /src

include ../Makefile.inc

.PHONY: all main core clean

all: main core

main:
	( cd main ; $(MAKE) )

core:
	( cd core ; $(MAKE) )

clean:
	( cd main ; $(MAKE) clean )
	( cd core ; $(MAKE) clean )
